name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        submodules: recursive

    #- uses: Jimver/cuda-toolkit@v0.2.15
    #  id: cuda-toolkit
    #  with:
    #    cuda: '12.4.1'

    #- run: nvcc -V

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'

    - name: Install setuptools
      run: python -m pip install --upgrade pip setuptools

    # This should hopefully work
    - name: Cache pip modules
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Sanity Check - List pip modules
      run: python -m pip list

    - name: Run build script
      run: python build.py --venv

    - name: Extract version
      id: get_version
      run: |
        echo ::set-output name=VERSION::$(python -c "from main import scriptVersion; print(scriptVersion)")
    - name: Print version
      id: print_version
      run: |
        python -c "from main import scriptVersion; print(scriptVersion)"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TAS }}
      with:
        tag_name: TAS_${{ steps.get_version.outputs.VERSION }}
        release_name: TAS_${{ steps.get_version.outputs.VERSION }}
        draft: true

    - name: Compress main directory
      run: 7z a TAS_${{ steps.get_version.outputs.VERSION }}.7z ~dist/main/

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TAS }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: TAS_${{ steps.get_version.outputs.VERSION }}.7z
        asset_name: TAS_${{ steps.get_version.outputs.VERSION }}.7z
        asset_content_type: application/x-7z-compressed