name: Build-macOS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "build.py"
      - "extra-requirements-macos.txt"
      - "extra-requirements-macos-lite.txt"
      - "requirements.txt"

permissions:
  contents: write

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv and Python
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: "3.14.5"
          version: "0.11.28"
          enable-cache: true

      - name: Extract version
        id: get_version
        run: |
          version=$(uv run --no-project python -c 'import src.version; print(src.version.__version__)')
          version_nodots=${version//./}
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "version_nodots=${version_nodots}" >> $GITHUB_OUTPUT

      - name: Run full build script
        run: uv run --no-project python build.py

      - name: Compress full directory
        run: |
          cd "${{ github.workspace }}/dist-portable/main/"
          tar -czf "../../TAS-${{ steps.get_version.outputs.version_nodots }}-macOS-arm64.tar.gz" .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TAS-${{ steps.get_version.outputs.version_nodots }}-macOS-arm64
          path: TAS-${{ steps.get_version.outputs.version_nodots }}-macOS-arm64.tar.gz
          if-no-files-found: error
