name: Ruff
on: [push, pull_request, workflow_dispatch]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Ruff with --fix option
        uses: chartboost/ruff-action@v1
        with:
          args: --fix-only