name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run build script
      run: python build.py

    - name: Extract version
      id: get_version
      run: |
        echo ::set-output name=VERSION::$(python -c "from main import scriptVersion; print(scriptVersion)")

    - name: Print version
      id: print_version
      run: |
        python -c "from main import scriptVersion; print(scriptVersion)"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: TAS_${{ steps.get_version.outputs.VERSION }}
        release_name: TAS_${{ steps.get_version.outputs.VERSION }}
        draft: true