name: Test-Windows-Build-Old

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.4"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Run build script
        run: python build.py --output dist-full

      - name: Run build-lite script
        run: python build-lite.py --output dist-lite

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TAS }}
        with:
          tag_name: TAS_
          release_name: TAS_
          draft: true

      - name: Compress full directory
        run: |
          cd ${{ github.workspace }}/dist-full/main/
          7z a -t7z -m0=lzma2 -mx=9 -ms=1536m -md=273m ../../TAS_Full_.7z *

      - name: Compress lite directory
        run: |
          cd ${{ github.workspace }}/dist-lite/main/
          7z a -t7z -m0=lzma2 -mx=9 -ms=1536m -md=273m ../../TAS_Lite_.7z *

      - name: Upload Full Release Asset
        id: upload-full-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TAS }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TAS_Full_.7z
          asset_name: TAS_Full_.7z
          asset_content_type: application/x-7z-compressed

      - name: Upload Lite Release Asset
        id: upload-lite-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TAS }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TAS_Lite_.7z
          asset_name: TAS_Lite_.7z
          asset_content_type: application/x-7z-compressed
