name: Test-Linux-Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.4"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Run build script
        run: python build-linux.py --output dist-full

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TAS }}
        with:
          tag_name: TAS_
          release_name: TAS_
          draft: true

      - name: Compress full directory
        run: |
          cd ${{ github.workspace }}/dist-full/main/
          tar -czvf ../../TAS_Full_.tar.gz *

      - name: Upload Full Release Asset
        id: upload-full-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TAS }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TAS_Full_.tar.gz
          asset_name: TAS_Full_.tar.gz
          asset_content_type: application/gzip
