name: Test-Version-Extraction

on:
  workflow_dispatch:

jobs:
  test_version_extraction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.4"

      - name: Extract version
        id: get_version
        run: echo "version=$(python -c 'import src.version; print(src.version.__version__)')" >> $GITHUB_ENV

      - name: Print version
        id: print_version
        run: echo "${{ env.version }}"